# Generated by Django 5.0.6 on 2024-12-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_proyecto_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='proyecto', verbose_name='Imagen'),
        ),
    ]
