# Generated by Django 5.0.6 on 2024-12-03 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_link_page_subtitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order', 'title'], 'verbose_name': 'página', 'verbose_name_plural': 'pages'},
        ),
    ]
