# Generated by Django 5.0.7 on 2024-08-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Imagen'),
        ),
    ]
