# Generated by Django 5.0.7 on 2024-08-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0002_remove_ejercicio_subtitle_ejercicio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ejercicio', verbose_name='Imagen'),
        ),
    ]
