# Generated by Django 5.0.7 on 2024-08-12 05:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0003_alter_ejercicio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Descripción'),
        ),
    ]
