# Generated by Django 5.0.7 on 2024-08-26 07:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0006_alter_ejercicio_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio_coop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ejercicio', verbose_name='Imagen')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descripción')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Dirección Web')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
            ],
            options={
                'verbose_name': 'ejercicio',
                'verbose_name_plural': 'ejercicios',
                'ordering': ['created'],
            },
        ),
    ]
