# Generated by Django 5.0.7 on 2024-08-26 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0007_ejercicio_coop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ejercicio_coop',
        ),
    ]
