# Generated by Django 5.0.7 on 2024-08-08 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habito',
            options={'ordering': ['created'], 'verbose_name': 'habito', 'verbose_name_plural': 'habitos'},
        ),
        migrations.RemoveField(
            model_name='habito',
            name='image',
        ),
    ]
