# Generated by Django 5.0.7 on 2024-08-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitos', '0002_alter_habito_options_remove_habito_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='habito',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='subtítulo'),
        ),
    ]
